### ISSUE TITLE
general error when update the explaination page settings

### ISSUE THREAD

**Issue by binghuiyin** [Feneck91/Introduciator#2]
一般错误
SQL ERROR [ mysqli ]

Data too long for column 'lang' at row 2 [1406]

SQL

INSERT INTO phpbb_introduciator_explanation (lang, message_title, message_title_uid, message_title_bitfield, message_title_bbcode_options, message_text, message_text_uid, message_text_bitfield, message_text_bbcode_options, rules_title, rules_title_uid, rules_title_bitfield, rules_title_bbcode_options, rules_text, rules_text_uid, rules_text_bitfield, rules_text_bbcode_options) VALUES ('en', '<t>%explanation_title%</t>', '', '', 7, '<t>%explanation_text%</t>', '', '', 7, '<t>%rules_title%</t>', '', '', 7, '<t>%rules_text%</t>', '', '', 7), ('zh_cmn_hans', '<t>%explanation_title%</t>', '', '', 7, '<t>%explanation_text%</t>', '', '', 7, '<t>%rules_title%</t>', '', '', 7, '<t>%rules_text%</t>', '', '', 7)

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 1023
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 195
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 682
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 393
CALL: phpbb\db\driver\driver->sql_multi_insert()

FILE: [ROOT]/ext/feneck91/introduciator/controller/acp_explanation_controller.php
LINE: 246
CALL: phpbb\db\driver\factory->sql_multi_insert()

FILE: [ROOT]/ext/feneck91/introduciator/controller/acp_explanation_controller.php
LINE: 111
CALL: feneck91\introduciator\controller\acp_explanation_controller->do_update_action()

FILE: [ROOT]/ext/feneck91/introduciator/acp/introduciator_module.php
LINE: 93
CALL: feneck91\introduciator\controller\acp_explanation_controller->do_action()

FILE: [ROOT]/includes/functions_module.php
LINE: 676
CALL: feneck91\introduciator\acp\introduciator_module->main()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()

**Comment by Feneck91** [comment]
Hi David, 

Thanks tou your reply. 

I'll see the problem this week-end. 
The version needed is at least phpBB 3.2.8 (I have a patch into phpBB to make my extension work): https://tracker.phpbb.com/browse/PHPBB3-15946 
You reply, you translate (so fast). 
But my account is not activated. Could you activate it manually ? 

Best regards, 
Stéphane (Feneck91) 

----- Mail original -----

De: "David Yin" <notifications@github.com> 
À: "Feneck91/Introduciator" <Introduciator@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Vendredi 21 Février 2020 10:21:50 
Objet: [Feneck91/Introduciator] general error when update the explaination page settings (#2) 



一般错误 
SQL ERROR [ mysqli ] 

Data too long for column 'lang' at row 2 [1406] 

SQL 

INSERT INTO phpbb_introduciator_explanation (lang, message_title, message_title_uid, message_title_bitfield, message_title_bbcode_options, message_text, message_text_uid, message_text_bitfield, message_text_bbcode_options, rules_title, rules_title_uid, rules_title_bitfield, rules_title_bbcode_options, rules_text, rules_text_uid, rules_text_bitfield, rules_text_bbcode_options) VALUES ('en', '%explanation_title%', '', '', 7, '%explanation_text%', '', '', 7, '%rules_title%', '', '', 7, '%rules_text%', '', '', 7), ('zh_cmn_hans', '%explanation_title%', '', '', 7, '%explanation_text%', '', '', 7, '%rules_title%', '', '', 7, '%rules_text%', '', '', 7) 

BACKTRACE 

FILE: (not given by php) 
LINE: (not given by php) 
CALL: msg_handler() 

FILE: [ROOT]/phpbb/db/driver/driver.php 
LINE: 1023 
CALL: trigger_error() 

FILE: [ROOT]/phpbb/db/driver/mysqli.php 
LINE: 195 
CALL: phpbb\db\driver\driver->sql_error() 

FILE: [ROOT]/phpbb/db/driver/driver.php 
LINE: 682 
CALL: phpbb\db\driver\mysqli->sql_query() 

FILE: [ROOT]/phpbb/db/driver/factory.php 
LINE: 393 
CALL: phpbb\db\driver\driver->sql_multi_insert() 

FILE: [ROOT]/ext/feneck91/introduciator/controller/acp_explanation_controller.php 
LINE: 246 
CALL: phpbb\db\driver\factory->sql_multi_insert() 

FILE: [ROOT]/ext/feneck91/introduciator/controller/acp_explanation_controller.php 
LINE: 111 
CALL: feneck91\introduciator\controller\acp_explanation_controller->do_update_action() 

FILE: [ROOT]/ext/feneck91/introduciator/acp/introduciator_module.php 
LINE: 93 
CALL: feneck91\introduciator\controller\acp_explanation_controller->do_action() 

FILE: [ROOT]/includes/functions_module.php 
LINE: 676 
CALL: feneck91\introduciator\acp\introduciator_module->main() 

FILE: [ROOT]/adm/index.php 
LINE: 81 
CALL: p_master->load_active()

**Comment by Feneck91** [comment]
This is because the langage tag (iso) was coded into 2 char, in fact it must be 30 char length.
Disable extension, clear datas, install new one and activate it, it is corrected.
